#!/usr/bin/env python3
"""
FineTuneForge Training Script
==============================
This script is generated by FineTuneForge and runs a LoRA fine-tuning job
using Hugging Face Transformers + PEFT on CPU.

Usage:
    python3 train.py --job-id <id> --model-id <model> --csv-path <path>
                     --text-column <col> --label-column <col>
                     --epochs <n> --lr <lr> --lora-rank <r>
                     --output-dir <dir>
"""

import argparse
import json
import os
import pickle
import sys
import warnings

warnings.filterwarnings("ignore")

import pandas as pd

# ---------------------------------------------------------------------------
# Argument parsing
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser(description="FineTuneForge Training Script")
parser.add_argument("--job-id", required=True)
parser.add_argument("--model-id", required=True)
parser.add_argument("--csv-path", required=True)
parser.add_argument("--text-column", required=True)
parser.add_argument("--label-column", required=True)
parser.add_argument("--epochs", type=int, default=1)
parser.add_argument("--lr", type=float, default=2e-4)
parser.add_argument("--lora-rank", type=int, default=8)
parser.add_argument("--output-dir", required=True)
args = parser.parse_args()

os.makedirs(args.output_dir, exist_ok=True)

def log(msg: str):
    """Print a log line and flush immediately."""
    print(msg, flush=True)


# ---------------------------------------------------------------------------
# Save the training script itself to output dir for download
# ---------------------------------------------------------------------------
def save_training_script():
    script_content = f'''#!/usr/bin/env python3
"""
FineTuneForge Generated Training Script
Model: {args.model_id}
Epochs: {args.epochs}
Learning Rate: {args.lr}
LoRA Rank: {args.lora_rank}
"""

import os
import warnings
import pandas as pd
import torch
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer,
)
from peft import LoraConfig, get_peft_model, TaskType
import pickle
import numpy as np
from sklearn.preprocessing import LabelEncoder

warnings.filterwarnings("ignore")

# ── Configuration ────────────────────────────────────────────────────────────
MODEL_ID = "{args.model_id}"
CSV_PATH = "{args.csv_path}"
TEXT_COLUMN = "{args.text_column}"
LABEL_COLUMN = "{args.label_column}"
NUM_EPOCHS = {args.epochs}
LEARNING_RATE = {args.lr}
LORA_RANK = {args.lora_rank}
OUTPUT_DIR = "./output"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ── Data loading ─────────────────────────────────────────────────────────────
print("[1/6] Loading dataset...")
df = pd.read_csv(CSV_PATH)
df = df.dropna(subset=[TEXT_COLUMN, LABEL_COLUMN])
df[TEXT_COLUMN] = df[TEXT_COLUMN].astype(str)

# Encode labels to integers
label_encoder = LabelEncoder()
df["encoded_label"] = label_encoder.fit_transform(df[LABEL_COLUMN].astype(str))
num_labels = len(label_encoder.classes_)
print(f"  Loaded {{len(df)}} rows | {{num_labels}} classes: {{list(label_encoder.classes_)}}")

# Train/eval split (80/20)
split_idx = int(len(df) * 0.8)
train_df = df.iloc[:split_idx].reset_index(drop=True)
eval_df = df.iloc[split_idx:].reset_index(drop=True)

# ── Tokenizer ────────────────────────────────────────────────────────────────
print("[2/6] Loading tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

def tokenize(batch):
    return tokenizer(
        batch[TEXT_COLUMN],
        truncation=True,
        padding="max_length",
        max_length=128,
    )

train_dataset = Dataset.from_pandas(train_df[[TEXT_COLUMN, "encoded_label"]])
eval_dataset = Dataset.from_pandas(eval_df[[TEXT_COLUMN, "encoded_label"]])
train_dataset = train_dataset.map(tokenize, batched=True)
eval_dataset = eval_dataset.map(tokenize, batched=True)
train_dataset = train_dataset.rename_column("encoded_label", "labels")
eval_dataset = eval_dataset.rename_column("encoded_label", "labels")
train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
eval_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])

# ── Model + LoRA ─────────────────────────────────────────────────────────────
print("[3/6] Loading base model and applying LoRA...")
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_ID,
    num_labels=num_labels,
    ignore_mismatched_sizes=True,
)
if model.config.pad_token_id is None:
    model.config.pad_token_id = tokenizer.pad_token_id

lora_config = LoraConfig(
    task_type=TaskType.SEQ_CLS,
    r={args.lora_rank},
    lora_alpha={args.lora_rank * 2},
    lora_dropout=0.1,
    bias="none",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# ── Training ─────────────────────────────────────────────────────────────────
print("[4/6] Starting training...")
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs={args.epochs},
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate={args.lr},
    weight_decay=0.01,
    evaluation_strategy="epoch",
    save_strategy="no",
    logging_steps=10,
    no_cuda=True,
    report_to="none",
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    accuracy = (preds == labels).mean()
    return {{"accuracy": float(accuracy)}}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    compute_metrics=compute_metrics,
)

train_result = trainer.train()
eval_result = trainer.evaluate()

# ── Save model ───────────────────────────────────────────────────────────────
print("[5/6] Saving fine-tuned model...")
model_path = os.path.join(OUTPUT_DIR, "model.pkl")
with open(model_path, "wb") as f:
    pickle.dump({{
        "model_state_dict": model.state_dict(),
        "label_encoder_classes": label_encoder.classes_.tolist(),
        "model_id": MODEL_ID,
        "lora_rank": LORA_RANK,
        "num_labels": num_labels,
    }}, f)

# ── Metrics ──────────────────────────────────────────────────────────────────
print("[6/6] Training complete!")
train_loss = train_result.training_loss
eval_loss = eval_result.get("eval_loss")
accuracy = eval_result.get("eval_accuracy")
print(f"  Train loss: {{train_loss:.4f}}")
if eval_loss: print(f"  Eval loss: {{eval_loss:.4f}}")
if accuracy: print(f"  Accuracy: {{accuracy*100:.2f}}%")

metrics = {{
    "train_loss": train_loss,
    "eval_loss": eval_loss,
    "accuracy": accuracy,
}}
with open(os.path.join(OUTPUT_DIR, "metrics.json"), "w") as f:
    json.dump(metrics, f)

print("Done!")
'''
    script_path = os.path.join(args.output_dir, "train_script.py")
    with open(script_path, "w") as f:
        f.write(script_content)


save_training_script()

# ---------------------------------------------------------------------------
# Actual training logic
# ---------------------------------------------------------------------------
try:
    log("[1/6] Loading dataset...")
    df = pd.read_csv(args.csv_path)
    df = df.dropna(subset=[args.text_column, args.label_column])
    df[args.text_column] = df[args.text_column].astype(str)
    log(f"  Loaded {len(df)} rows from {os.path.basename(args.csv_path)}")

    # Encode labels
    from sklearn.preprocessing import LabelEncoder
    label_encoder = LabelEncoder()
    df["encoded_label"] = label_encoder.fit_transform(df[args.label_column].astype(str))
    num_labels = len(label_encoder.classes_)
    log(f"  Found {num_labels} classes: {list(label_encoder.classes_[:10])}")

    # Train/eval split
    split_idx = int(len(df) * 0.8)
    train_df = df.iloc[:split_idx].reset_index(drop=True)
    eval_df = df.iloc[split_idx:].reset_index(drop=True)
    log(f"  Train: {len(train_df)} samples | Eval: {len(eval_df)} samples")

    log("[2/6] Loading tokenizer...")
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(args.model_id)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    log(f"  Tokenizer loaded: {args.model_id}")

    log("[3/6] Tokenizing dataset...")
    from datasets import Dataset

    def tokenize(batch):
        return tokenizer(
            batch[args.text_column],
            truncation=True,
            padding="max_length",
            max_length=128,
        )

    train_dataset = Dataset.from_pandas(train_df[[args.text_column, "encoded_label"]])
    eval_dataset = Dataset.from_pandas(eval_df[[args.text_column, "encoded_label"]])
    train_dataset = train_dataset.map(tokenize, batched=True, desc="Tokenizing train")
    eval_dataset = eval_dataset.map(tokenize, batched=True, desc="Tokenizing eval")
    train_dataset = train_dataset.rename_column("encoded_label", "labels")
    eval_dataset = eval_dataset.rename_column("encoded_label", "labels")
    train_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
    eval_dataset.set_format("torch", columns=["input_ids", "attention_mask", "labels"])
    log("  Tokenization complete")

    log("[4/6] Loading base model and applying LoRA...")
    import torch
    from transformers import AutoModelForSequenceClassification
    from peft import LoraConfig, get_peft_model, TaskType

    model = AutoModelForSequenceClassification.from_pretrained(
        args.model_id,
        num_labels=num_labels,
        ignore_mismatched_sizes=True,
    )
    if model.config.pad_token_id is None:
        model.config.pad_token_id = tokenizer.pad_token_id

    lora_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        r=args.lora_rank,
        lora_alpha=args.lora_rank * 2,
        lora_dropout=0.1,
        bias="none",
    )
    model = get_peft_model(model, lora_config)
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    log(f"  Trainable parameters: {trainable_params:,} / {total_params:,} ({100*trainable_params/total_params:.2f}%)")

    log("[5/6] Training...")
    from transformers import TrainingArguments, Trainer
    import numpy as np

    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        learning_rate=args.lr,
        weight_decay=0.01,
        eval_strategy="epoch",
        save_strategy="no",
        logging_steps=5,
        no_cuda=True,
        report_to="none",
        disable_tqdm=True,
    )

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)
        accuracy = float((preds == labels).mean())
        return {"accuracy": accuracy}

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        compute_metrics=compute_metrics,
    )

    train_result = trainer.train()
    log(f"  Training finished. Loss: {train_result.training_loss:.4f}")

    eval_result = trainer.evaluate()
    train_loss = float(train_result.training_loss)
    eval_loss = float(eval_result.get("eval_loss", 0))
    accuracy = float(eval_result.get("eval_accuracy", 0))

    log("[6/6] Saving model and metrics...")
    model_path = os.path.join(args.output_dir, "model.pkl")
    with open(model_path, "wb") as f:
        pickle.dump({
            "model_state_dict": model.state_dict(),
            "label_encoder_classes": label_encoder.classes_.tolist(),
            "model_id": args.model_id,
            "lora_rank": args.lora_rank,
            "num_labels": num_labels,
        }, f)
    log(f"  Model saved to {model_path}")

    metrics = {"train_loss": train_loss, "eval_loss": eval_loss, "accuracy": accuracy}
    with open(os.path.join(args.output_dir, "metrics.json"), "w") as f:
        json.dump(metrics, f)

    log(f"[FineTuneForge] DONE — train_loss={train_loss:.4f} eval_loss={eval_loss:.4f} accuracy={accuracy*100:.2f}%")
    sys.exit(0)

except Exception as e:
    import traceback
    log(f"[ERROR] {str(e)}")
    log(traceback.format_exc())
    sys.exit(1)
